name: publish
on:
  push:
    tags:
      - v*
jobs:
  publish-binaries:
    defaults:
      run:
        shell: bash
    runs-on: akashi
    # Using custom ArchLinux based action runner from private registry
    container:
      image: gitea-service:80/actions/arch-action-runner-full:latest
      options: "--security-opt seccomp=unconfined --security-opt apparmor=unconfined --device /dev/fuse:rw" # container setup for buildah
      credentials:
        username:  ${{secrets.REGISTRY_USERNAME}}
        password:  ${{secrets.REGISTRY_ACCESS_TOKEN}}
    steps:
      - uses: http://gitea-service/actions/checkout@v4
        with:
          show-progress: false
          submodules: true
      - name: Setup rustup targets and pnpm
        run: |
          rustup default stable;
          rustup target add aarch64-unknown-linux-gnu \
          aarch64-unknown-linux-musl \
          arm-unknown-linux-musleabi \
          armv7-unknown-linux-musleabi \
          riscv64gc-unknown-linux-gnu \
          x86_64-unknown-linux-gnu \
          x86_64-unknown-linux-musl;
      - name: Init project
        run: make init
      - name: Run tests
        run: make test
      - name: Build binaries and pack
        run: >
          export CARGO_TERM_QUIET=true;
          make pack
      - name: Build container images
        run: >
          make gen-dockerfiles;
          ./tools/build_images.sh \
            -c "build.config.json" \
            -a "bin/dockerfiles/annotations.json" \
            -f "bin/dockerfiles" \
            -r "${REGISTRY_URL}" \
            -u "${REGISTRY_USERNAME}" \
            -p "${REGISTRY_PASSWORD}";
        env:
          REGISTRY_URL: ${{secrets.REGISTRY_URL}}
          REGISTRY_USERNAME: ${{secrets.REGISTRY_USERNAME}}
          REGISTRY_PASSWORD: ${{secrets.REGISTRY_ACCESS_TOKEN}}
      - name: Generate release body from changelog
        run: >
          VERSION="$(cat "./bin/dockerfiles/annotations.json" | jq -r '.version')"
          cat ./CHANGELOG | awk -v version="^# v${VERSION}" '$0 ~ version {start=1;next}/^# v.*$/{start=0}start' > release_body.txt;
          cat ./release_body.txt;
      - name: Crete draft release with binaries
        uses: http://gitea-service/actions/gitea-release-action@main
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: false
        with:
          files: |-
            bin/dist/**
          api_key: ${{secrets.RELEASE_TOKEN}}
          title: ${{vars.GITEA_REF_NAME}}
          body_path: "./release_body.txt"
