name: test
on: push
jobs:
  publish-binaries:
    defaults:
      run:
        shell: bash
    runs-on: akashi
    container:
      image: gitea-service:80/actions/arch-action-runner-full:latest
      credentials:
        username:  ${{secrets.REGISTRY_USERNAME}}
        password:  ${{secrets.REGISTRY_ACCESS_TOKEN}}
    steps:
      - uses: http://gitea-service/actions/checkout@v4
        with:
          show-progress: false
          submodules: true
      - name: Setup rustup targets
        run: |
          rustup default stable
      - name: Init project
        run: make init
      - name: Run checks
        run: make check
      - name: Run tests
        run: make test
